language: generic
sudo: required

services:
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - sleep 15
  - mongodb
  - docker

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server

install:
  - sudo curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get update
  - sudo apt-get install -y nodejs
  - sudo apt-get install -y npm || true
  - ( cd inbeat && sudo ./install.sh )
  - travis_wait 60 docker build -t inbeat .
  - docker run -d -p 8880:80 --name inbeat inbeat

before_script:
  - sleep 15

script:
  - ( cd inbeat/inbeat-bl && npm test)
  - docker ps | grep -q inbeat
  - ( cd tests && ./main-scenario-integration-test.sh )
